### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by joshski** [featurist/plastiq#10]
Just adding this so it's not an afterthought! ...which it is, already, to some extent :neckbeard:

**Comment by refractalize** [comment]
Yes good point.

There are some other projects that can help us here, see [vdom-to-html](https://github.com/Matt-Esch/virtual-dom/wiki#vdom-to-html), [html-to-vdom](https://github.com/Matt-Esch/virtual-dom/wiki#dom-to-vdom) and [dom-to-vdom](https://github.com/Matt-Esch/virtual-dom/wiki#dom-to-vdom).

In theory we use [virtual-dom-stringify](https://github.com/alexmingoia/virtual-dom-stringify/) to produce the HTML on the server, then reconstruct the original vdom using [vdom-virtualize](https://github.com/marcelklehr/vdom-virtualize/).

**Comment by joshski** [comment]
There are some server-side examples [in the tests](../tree/master/test/server) now.
