### ISSUE TITLE
Plastiq doesn't really have components

### ISSUE THREAD

**Issue by joshski** [featurist/plastiq#11]
The line "Plastiq doesn't really have components" in the readme is a bit odd, now that plastiq has components.

**Comment by refractalize** [comment]
true, and the components documentation is talking about features that don't exist! (the bit where you can return a component from an event handler to get it to render just that component.)

**Comment by refractalize** [comment]
commit 5a22670337359bb708b9077f360c574e53d52004 allows you to return a component from an event handler to render just that component (for performance reasons). So that's the documentation fixed.
