### ISSUE TITLE
router history parameter?

### ISSUE THREAD

**Issue by joshski** [featurist/plastiq#31]
master mocha tests are [failing](https://travis-ci.org/featurist/plastiq/builds/51806564) because there is no `window` in the new history abstraction.

A router is currently defined like this:

```JavaScript
h('div',
   router(
      router.page('/', function () {})
   )
)
```

So I was wondering, since both `router` and `router.page` need access to the history abstraction, do you see it as a global thing?

This might be better:

```JavaScript
var router = plastiq.router({ history: myHistoryApi });

...

h('div',
   router(
      router.page('/', function () {})
   )
)
```

wdyt?

**Comment by refractalize** [comment]
Yeah I think that's right. Though I want to have a simpler API for the common case (in browser) - not sure how we'd do both at the moment...

**Comment by joshski** [comment]
isn't that just a question of:
```JavaScript
var router = plastiq.router;
```
vs...
```JavaScript
var router = plastiq.router();
```
?

**Comment by joshski** [comment]
even the browser case probably wants to choose between hash or history, so perhaps:

```
var router = plastiq.router({ history: 'html5' });
```

**Comment by refractalize** [comment]
yeah, perhaps having to create a router isn't so bad, even in the common case

**Comment by refractalize** [comment]
I've done the behind the scenes work in ae58192ab5c1b5af7fae0526e6e1b7eb26c0aeb7, router is now an object. Havne't exposed it as `plastiq.router` yet, not can you create a new one yourself, but getting there.

**Comment by refractalize** [comment]
API is `var router = plastiq.router([options])`, as of 11112478c30ed8b2f4c9aaf3b6329968ed3b74e6
