### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by daiyam** [featurist/plastiq#54]
Hi,

I've updated a benchmark to include your framework but I know it can do better since I don't use any components. I've tried but failed :(

If you can take a look, it would be very helpful.

[repository](https://github.com/daiyam/js-framework-benchmark) - [results](https://output.jsbin.com/lohibu/)

Thx

**Comment by refractalize** [comment]
Thanks @daiyam,

I've made a pull request here: https://github.com/daiyam/js-framework-benchmark/pull/1

**Comment by daiyam** [comment]
Thanks @refractalize 

I was hoping to have the rows as components...
Anyways, [here](https://rawgit.com/daiyam/js-framework-benchmark/master/webdriver-java/table.html) are the results (on my old machine).

I've also made a pull request to [krausest/js-framework-benchmark](https://github.com/krausest/js-framework-benchmark/pull/4)
